### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by grlee77**
rerender to get python 3.6 and numpy 1.12 builds

### CODE REVIEW

**Comment by grlee77** [comment]
no idea why the sha256 would have changed.  I downloaded it locally and get the same sha256 as the previous failed run on CircleCI.  I guess the archive was updated at github since the last time this was run.

**Comment by grlee77** [comment]
May need to raise an issue related to numpy 1.12 at scikit-sparse

CirceCI failed during the test stage for numpy 1.12, python 2.7.  The two test failures are:
```
======================================================================
ERROR: sksparse.test_cholmod.test_complex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/sksparse/test_cholmod.py", line 99, in test_complex
    assert_allclose(fc(np.arange(4) * 1j)[:, None],
  File "sksparse/cholmod.pyx", line 850, in sksparse.cholmod.Factor.__call__ (sksparse/cholmod.c:10546)
  File "sksparse/cholmod.pyx", line 846, in sksparse.cholmod.Factor.solve_A (sksparse/cholmod.c:10397)
  File "sksparse/cholmod.pyx", line 899, in sksparse.cholmod.Factor._solve (sksparse/cholmod.c:11850)
  File "sksparse/cholmod.pyx", line 924, in sksparse.cholmod.Factor._solve_dense (sksparse/cholmod.c:12350)
  File "sksparse/cholmod.pyx", line 369, in sksparse.cholmod._error_handler (sksparse/cholmod.c:4399)
CholmodInvalidError: ../Cholesky/cholmod_solve.c:1079: dimensions of L and B do not match (code -4)

======================================================================
ERROR: sksparse.test_cholmod.test_cholesky_matrix_market
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/feedstock_root/build_artefacts/recipe_root_1486080708541/_t_env/lib/python2.7/site-packages/sksparse/test_cholmod.py", line 171, in test_cholesky_matrix_market
    assert_allclose(cholesky(XtX, mode=mode)(Xty), answer)
  File "sksparse/cholmod.pyx", line 850, in sksparse.cholmod.Factor.__call__ (sksparse/cholmod.c:10546)
  File "sksparse/cholmod.pyx", line 846, in sksparse.cholmod.Factor.solve_A (sksparse/cholmod.c:10397)
  File "sksparse/cholmod.pyx", line 899, in sksparse.cholmod.Factor._solve (sksparse/cholmod.c:11850)
  File "sksparse/cholmod.pyx", line 924, in sksparse.cholmod.Factor._solve_dense (sksparse/cholmod.c:12350)
  File "sksparse/cholmod.pyx", line 369, in sksparse.cholmod._error_handler (sksparse/cholmod.c:4399)
CholmodInvalidError: ../Cholesky/cholmod_solve.c:1079: dimensions of L and B do not match (code -4)
```

**Comment by grlee77** [comment]
I believe the sha256 change was due to the same thing discussed here:
https://groups.google.com/forum/?hl=en#!topic/conda-forge/GyiK4FHECZY

**Comment by grlee77** [comment]
The test failures above should be fixed by scikit-sparse/scikit-sparse#28

**Comment by jor-** [comment]
Version 0.4.1 of scikit-sparse is released. (See scikit-sparse/scikit-sparse#27.) This should fix this bug

**Comment by grlee77** [comment]
Thanks @jor-, v0.4.1 packages built successfully.

**Comment by jor-** [comment]
@grlee77: Thank you for making this updated build.

**Pull request merged**
