### PR TITLE
restore proper permissions of conda-forge.yml

### PR DESCRIPTION
**Pull request by grlee77**

### CODE REVIEW

**Comment by grlee77** [comment]
forgot [skip ci].  will manually cancel it.

**Comment by grlee77** [comment]
@jakirkham 
This just restores the permissions back to the proper values.  I assume this can just be merged without changing the build number?

**Comment by grlee77** [comment]
incorporated in #6 instead

**Comment by jakirkham** [comment]
> This just restores the permissions back to the proper values. I assume this can just be merged without changing the build number?

Sorry, missed this one. Yeah no build number bump required. `conda-forge.yml` simply exists to configure the feedstock. Changing its permissions has no net effect on the packages built.

**Pull request closed without merging**
