### PR TITLE
add packages for numpy 1.13

### PR DESCRIPTION
**Pull request by jor-**
It would be nice to have packages for numpy 1.13 too.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please don't change the CI files manually. Please just [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) and these changes should be taken care of automatically.

**Comment by jor-** [comment]
Thank you for the hint. I re-rendered it now with conda smithy.

**Comment by jor-** [comment]
Should I merge this PR?

**Comment by jakirkham** [comment]
LGTM. @grlee77? @patricksnape?

**Comment by grlee77** [comment]
sure.  LGTM

**Pull request merged**
